version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENV PORT=5000
      - ENV MONGO_URI=mongodb+srv://sanketrathod7420:XDeQeFXCtJivkq0O@backendsystemqqueue.jhxkh.mongodb.net/?retryWrites=true&w=majority&appName=backendSystemqQueue
      - ENV JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
      - ENV RABBITMQ_URI=amqp://localhost
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/config/db
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
